### ISSUE TITLE
cannot open anything via file open dialog on KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [flathub/io.github.celluloid_player.Celluloid#10]
I use celluloid 0.20 on Arch Linux running KDE Plasma 5.20 beta desktop environment.
File open dialog does not find any video file, "Filter" combobox on bottom is empty.

![celluloid](https://user-images.githubusercontent.com/15967631/95237391-86c31c80-07de-11eb-9ea1-078f36825840.png)

**Comment by Bananaman** [comment]
I can tell you that it works with Nautilus on Pop!_OS (Ubuntu 20.10 based.

To be able to see files in the "open" dialog, your desktop environment needs to have "portals" support.

**Comment by glaubersm** [comment]
KDE Plasma supports portals, both xdg-desktop-portal and xdg-desktop-portal-kde packages are installed on my system.

I think that default permissions should be configured to make Celluloid fully usable.

**Comment by glaubersm** [comment]
This bug persists. File open dialog is unusable on Arch Linux running Plasma 5.24.

**Comment by TingPing** [comment]
It sounds like a bug in `xdg-desktop-portal-kde`.

**Comment by glaubersm** [comment]
I have several flatpaks installed on my system, Celluloid is the only one affected by this bug.
Are you able to reproduce on your system? What desktop environmnet are you sing?

I see this output in terminal when I run Celluloid and open the file open dialog:
```
$ flatpak run io.github.celluloid_player.Celluloid
Cannot load libcuda.so.1

(io.github.celluloid_player.Celluloid:2): Gtk-WARNING **: 18:06:35.283: Failed to measure available space: Error getting filesystem info for /mnt/2TB: No such file or directory

(io.github.celluloid_player.Celluloid:2): Gtk-WARNING **: 18:06:35.283: Failed to measure available space: Error getting filesystem info for /mnt/WD: No such file or directory

(io.github.celluloid_player.Celluloid:2): Gtk-WARNING **: 18:06:35.283: Failed to measure available space: Error getting filesystem info for /mnt/WIN7: No such file or directory

(io.github.celluloid_player.Celluloid:2): Gtk-WARNING **: 18:06:35.283: Failed to measure available space: Error getting filesystem info for /mnt/SEAGATE: No such file or directory

(io.github.celluloid_player.Celluloid:2): GLib-CRITICAL **: 18:06:37.054: Source ID 968 was not found when attempting to remove it
```

**Comment by TingPing** [comment]
I am on GNOME, the file chooser functions fine. For filters it lists "Video files", "Audio files", etc.

**Comment by nicolasfella** [comment]
> However, Celluloid sends the filter `images/*`, which should probably be `image/*`, so that it matches `image/png`, `image/jpeg`, etc

This is also broken for the non-Flatpak version with the GTK file dialog. Selecting the "Image files" filter doesn't list any files, not even image files

**Comment by TingPing** [comment]
@nicolasfella Thanks!

Fixed that here: https://github.com/celluloid-player/celluloid/pull/752

**Comment by firefoxlover** [comment]
uhm, so should this issue be closed? KDEs Portal works completely fine

**Comment by glaubersm** [comment]
This bug persists on Arch Linux running Celluloid 0.26 and xdg-desktop-portal-kde 5.27.10-1.

**Comment by TingPing** [comment]
Unless you have some strong evidence otherwise your issue likely has nothing to do with this app.

**Comment by TingPing** [comment]
KDE never fixed their bug above: https://invent.kde.org/frameworks/kio/-/merge_requests/766
